In [1]:
import ROOT as root
import numpy as np
import simulacion as s

Welcome to JupyROOT 6.30/04


# 3. Forma de las distribuciones de uniformidad

## Histogramas sin defecto

In [124]:
h = []
Cmed_list = [2232,4464,8929,17857,35714]
nct_list = [5,10,20,40,80]

In [128]:

Cmed_list = [8929,17857,35714]
nct_list = [20,40,80]

N_pix = 64
num_cuentas = 10000

for C_med, nct in zip(Cmed_list,nct_list):
    dist = s.dist_defectos(0,0,N_pix,C_med,num_cuentas,3,11)
    name = s.histogram_name(N_pix,nct,1)
    hist = root.TH1D(name,'',400,0.,10.)
    print(dist)
    for i in range(len(dist)):
        hist.Fill(dist[i])
    hist.Scale(1.0/hist.Integral(),"width")
    sigma=s.incertidumbre(hist,num_cuentas)
    print(np.max(sigma))
    for i,error in enumerate(sigma,start=1):
        hist.SetBinError(i,error)
    h.append(hist)



[1.0690745  1.07452108 1.07890413 ... 1.80994248 1.8332569  1.84043778]
0.004963869458396343
[0.75865503 0.76623777 0.76807928 ... 1.28807351 1.2998193  1.30400562]
0.004980602373207482
[0.53393484 0.53533135 0.53645459 ... 0.90576596 0.9059964  0.93489471]
0.004737087712930805


In [129]:
graphs = []
for hist in h:
    graph = root.TGraphErrors(hist)
    sigma=s.incertidumbre(hist,num_cuentas)
    graph.SetLineColor(hist.GetMarkerColor())
    graph.SetLineWidth(2)
    graph.SetMarkerStyle(21)
    graph.SetMarkerSize(1.5)
    graphs.append(graph)

In [135]:
root.gROOT.SetStyle("ATLAS")
root.gROOT.ForceStyle()
canvas = root.TCanvas('', '', 1400, 1000)  # Increase width and height for higher resolution

legend = root.TLegend(0.65, 0.55, 0.85, 0.85)
legend.SetEntrySeparation(0.05)
legend.SetBorderSize(0)
legend.SetMargin(0.1)
legend.AddEntry(graphs[2],"M(64,5)")
legend.AddEntry(graphs[3],"M(64,10)")
legend.AddEntry(graphs[4],"M(64,20)")
legend.AddEntry(graphs[5],"M(64,40)")
legend.AddEntry(graphs[6],"M(64,80)")
legend.SetTextFont(42)  # 42 is the font code for LaTeX-compatible fonts
legend.SetTextSize(0.03)  # Adjust the font size as needed

graphs[2].SetMarkerColor(root.kBlue)
graphs[3].SetMarkerColor(root.kRed)
graphs[4].SetMarkerColor(root.kGreen)
graphs[5].SetMarkerColor(root.kOrange+7)
graphs[6].SetMarkerColor(root.kMagenta)

graphs[2].SetLineColor(root.kBlue)
graphs[3].SetLineColor(root.kRed)
graphs[4].SetLineColor(root.kGreen)
graphs[5].SetLineColor(root.kOrange+7)
graphs[6].SetLineColor(root.kMagenta)


# Draw the first TGraph with a smooth curve
graphs[0].SetLineWidth(3)
graphs[0].SetMarkerSize(1)
graphs[0].Draw("APL")

# Draw the remaining TGraphs with smooth curves
for i in range(1, len(graphs)):
    graphs[i].SetLineWidth(3)
    graphs[i].SetMarkerSize(1)
    graphs[i].Draw("PL SAME")


# Set titles and ranges
graphs[0].SetTitle("Distribuciones de uniformidad integral")
graphs[0].GetXaxis().SetTitle("Uniformidad integral")
graphs[0].GetYaxis().SetTitle("Densidad de probabilidad")
graphs[0].GetXaxis().SetTitleSize(0.035)  # Adjust as needed
graphs[0].GetYaxis().SetTitleSize(0.035)  # Adjust as needed
graphs[0].GetXaxis().CenterTitle()
graphs[0].GetYaxis().CenterTitle()
graphs[0].GetXaxis().SetTitleOffset(1.5) 
graphs[0].GetYaxis().SetTitleOffset(1.5)
graphs[0].GetYaxis().SetRangeUser(0, 10)
graphs[0].GetXaxis().SetRangeUser(0, 4)

legend.Draw()
canvas.SaveAs("distribucionessindefecto.png")

Info in <TCanvas::Print>: png file distribucionessindefecto.png has been created


In [136]:
# Assuming 'graphs' is a list of TGraphErrors objects you have created and styled

# Create a ROOT file to save the graphs
file = root.TFile("distribucionesUI.root", "RECREATE")

# Loop through each graph and write it to the ROOT file
for i, graph in enumerate(graphs):
    graph.SetName(f"graph_{i}")  # Set a unique name for each graph
    graph.Write()

# Close the ROOT file
file.Close()

print(f"Graphs saved to 'graphs.root'.")

Graphs saved to 'graphs.root'.


## Distribuciones con defecto 

### Comparativa distintos defectos

In [146]:
h = []

In [148]:
Cmed = 8929
nct = 20
t_list = [3]
k_list = [2,4,8]
media = np.zeros((len(t_list),len(k_list)))
varianza = np.zeros((len(t_list),len(k_list)))
N_pix = 64
num_cuentas = 20000

for i in range(len(t_list)):
    for j in range(len(k_list)):
        t = t_list[i]
        k = k_list[j]
        dist = s.dist_defectos(t,k,N_pix,Cmed,num_cuentas,3,11)
        name = s.histogram_name(N_pix,nct,1,t,k)
        hist = root.TH1D(name,'',400,0.,10.)
        for k in range(len(dist)):
            hist.Fill(dist[k])
        hist.Scale(1.0/hist.Integral(),"width")
        sigma=s.incertidumbre(hist,num_cuentas)
        for k,error in enumerate(sigma,start=1):
            hist.SetBinError(k,error)
        h.append(hist)
        
        

In [149]:
graphs = []
for hist in h:
    graph = root.TGraphErrors(hist)
    graph.SetLineColor(hist.GetMarkerColor())
    graph.SetLineWidth(2)
    graph.SetMarkerStyle(21)
    graph.SetMarkerSize(1.5)
    graphs.append(graph)

In [152]:
root.gROOT.SetStyle("ATLAS")
root.gROOT.ForceStyle()
canvas = root.TCanvas('', '', 1400, 1000)  # Increase width and height for higher resolution

legend = root.TLegend(0.65, 0.60, 0.85, 0.90)
legend.SetEntrySeparation(0.05)
legend.SetBorderSize(0)
legend.SetMargin(0.1)
legend.AddEntry(graphs[0],"M(64,20), D(2,2)")
legend.AddEntry(graphs[1],"M(64,20), D(2,4)")
legend.AddEntry(graphs[2],"M(64,20), D(2,8)")
legend.AddEntry(graphs[3],"M(64,20), D(3,2)")
legend.AddEntry(graphs[4],"M(64,20), D(3,4)")
legend.AddEntry(graphs[5],"M(64,20), D(3,8)")
legend.SetTextFont(42)  # 42 is the font code for LaTeX-compatible fonts
legend.SetTextSize(0.03)  # Adjust the font size as needed

graphs[0].SetMarkerColor(root.kAzure-4)
graphs[1].SetMarkerColor(root.kBlue)
graphs[2].SetMarkerColor(root.kBlue+3)
graphs[3].SetMarkerColor(root.kRed-7)
graphs[4].SetMarkerColor(root.kRed)
graphs[5].SetMarkerColor(root.kRed+3)

graphs[0].SetLineColor(root.kAzure-4)
graphs[1].SetLineColor(root.kBlue)
graphs[2].SetLineColor(root.kBlue+3)
graphs[3].SetLineColor(root.kRed-7)
graphs[4].SetLineColor(root.kRed)
graphs[5].SetLineColor(root.kRed+3)

graphs[3].SetMarkerStyle(20)
graphs[4].SetMarkerStyle(20)
graphs[5].SetMarkerStyle(20)

'''graphs[4].SetMarkerColor(1)
graphs[4].SetLineColor(graphs[4].GetMarkerColor())'''
# Draw the first TGraph with a smooth curve
graphs[0].SetLineWidth(3)
graphs[0].SetMarkerSize(1)
graphs[0].Draw("APL")

# Draw the remaining TGraphs with smooth curves
for i in range(1, len(graphs)):
    graphs[i].SetLineWidth(3)
    graphs[i].SetMarkerSize(1)
    graphs[i].Draw("PL SAME")


# Set titles and ranges
graphs[0].SetTitle("Distribuciones de uniformidad integral")
graphs[0].GetXaxis().SetTitle("Uniformidad integral")
graphs[0].GetYaxis().SetTitle("Densidad de probabilidad")
graphs[0].GetXaxis().SetTitleSize(0.035)  # Adjust as needed
graphs[0].GetYaxis().SetTitleSize(0.035)  # Adjust as needed
graphs[0].GetXaxis().CenterTitle()
graphs[0].GetYaxis().CenterTitle()
graphs[0].GetXaxis().SetTitleOffset(1.5) 
graphs[0].GetYaxis().SetTitleOffset(1.5)
graphs[0].GetYaxis().SetRangeUser(0, 4)
graphs[0].GetXaxis().SetRangeUser(0.5, 6)

legend.Draw()
canvas.SaveAs("distribucionesdefecto.png")


Info in <TCanvas::Print>: png file distribucionesdefecto.png has been created


In [ ]:
# Assuming 'graphs' is a list of TGraphErrors objects you have created and styled

# Create a ROOT file to save the graphs
file = root.TFile("distribucionesDEFECTO.root", "RECREATE")

# Loop through each graph and write it to the ROOT file
for i, graph in enumerate(graphs):
    graph.SetName(f"graph_{i}")  # Set a unique name for each graph
    graph.Write()

# Close the ROOT file
file.Close()

print(f"Graphs saved to 'graphs.root'.")